import Head from "next/head";
import { useInitializer } from "@/hooks/useInitializer";
import { ASCIIMaze } from "@/components/maze/ascii/ASCIIMaze";
import { useMovement } from "@/hooks/useMovement";

export default function Home() {
  const { squares, nX } = useInitializer({ nX: 14 });
  const { moveHandler } = useMovement();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section
        style={{
          display: "grid",
          placeItems: "center",
          width: "100dvw",
          height: "100dvh",
        }}
      >
        <ASCIIMaze {...{ squares, nX }} />
        <div>
          <button onClick={() => moveHandler(["ArrowLeft"])}>LEFT</button>
          <button onClick={() => moveHandler(["ArrowRight"])}>RIGHT</button>
          <button onClick={() => moveHandler(["ArrowDown"])}>DOWN</button>
          <button onClick={() => moveHandler(["ArrowUp"])}>UP</button>
        </div>
      </section>
    </>
  );
}
